//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifteenBelow.Deployment.ReportingServices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DeployHelp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeployHelp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("FifteenBelow.Deployment.ReportingServices.DeployHelp", typeof(DeployHelp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy either reports (.rdl files) or add a role to a local/domain user.
        ///
        ///Both options requires Reporting Service Variables (--rsv). multiple values can (and must) be specified. 
        ///
        ///Example Usage:
        ///
        ///# Deploy Reports
        ///	--dr
        ///	--rsv reportingServicesUrl=http://reportingservices.yourserver.com:80/ReportServer_INSTANCE/ReportService2010.asmx
        ///	--rsv networkDomain=DOMAIN
        ///	--rsv networkLogin=USER
        ///	--rsv networkPassword=PASSWORD
        ///	
        ///	--rsv parentFolder=PARENT_FOLDER 
        ///	--rsv subFolder=SUB_FOLDER
        ///	--rsv dataS [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ExampleUsage {
            get {
                return ResourceManager.GetString("ExampleUsage", resourceCulture);
            }
        }
    }
}
